apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: ccnp
  name: measurement-server
  labels:
    app.kubernetes.io/name: measurement-server
    app.kubernetes.io/instance: measurement-server
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: measurement-server
  namespace: ccnp
  labels:
    app.kubernetes.io/name: measurement-server
    app.kubernetes.io/instance: measurement-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: measurement-server
      app.kubernetes.io/instance: measurement-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: measurement-server
        app.kubernetes.io/instance: measurement-server
    spec:
      serviceAccountName: measurement-server
      securityContext:
        {}
      containers:
        - name: measurement-server
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop: ["NET_RAW"]
          image: "docker.io/library/ccnp-measurement-server:0.1"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command: ["/usr/bin/grpc_health_probe", "-addr=unix:/run/ccnp/uds/measurement.sock"]
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["/usr/bin/grpc_health_probe", "-addr=unix:/run/ccnp/uds/measurement.sock"]
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
              tdx.intel.com/tdx-guest: 1
            requests:
              tdx.intel.com/tdx-guest: 1
      nodeSelector:
        intel.feature.node.kubernetes.io/tdx-guest: enabled
