# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ccnp_server_pb2 as ccnp__server__pb2


class ccnpStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReport = channel.unary_unary(
                '/ccnp_server_pb.ccnp/GetReport',
                request_serializer=ccnp__server__pb2.GetReportRequest.SerializeToString,
                response_deserializer=ccnp__server__pb2.GetReportResponse.FromString,
                )
        self.GetMeasurement = channel.unary_unary(
                '/ccnp_server_pb.ccnp/GetMeasurement',
                request_serializer=ccnp__server__pb2.GetMeasurementRequest.SerializeToString,
                response_deserializer=ccnp__server__pb2.GetMeasurementResponse.FromString,
                )
        self.GetEventlog = channel.unary_unary(
                '/ccnp_server_pb.ccnp/GetEventlog',
                request_serializer=ccnp__server__pb2.GetEventlogRequest.SerializeToString,
                response_deserializer=ccnp__server__pb2.GetEventlogResponse.FromString,
                )


class ccnpServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMeasurement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventlog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ccnpServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReport,
                    request_deserializer=ccnp__server__pb2.GetReportRequest.FromString,
                    response_serializer=ccnp__server__pb2.GetReportResponse.SerializeToString,
            ),
            'GetMeasurement': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMeasurement,
                    request_deserializer=ccnp__server__pb2.GetMeasurementRequest.FromString,
                    response_serializer=ccnp__server__pb2.GetMeasurementResponse.SerializeToString,
            ),
            'GetEventlog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventlog,
                    request_deserializer=ccnp__server__pb2.GetEventlogRequest.FromString,
                    response_serializer=ccnp__server__pb2.GetEventlogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ccnp_server_pb.ccnp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ccnp(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ccnp_server_pb.ccnp/GetReport',
            ccnp__server__pb2.GetReportRequest.SerializeToString,
            ccnp__server__pb2.GetReportResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMeasurement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ccnp_server_pb.ccnp/GetMeasurement',
            ccnp__server__pb2.GetMeasurementRequest.SerializeToString,
            ccnp__server__pb2.GetMeasurementResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEventlog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ccnp_server_pb.ccnp/GetEventlog',
            ccnp__server__pb2.GetEventlogRequest.SerializeToString,
            ccnp__server__pb2.GetEventlogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
