apiVersion: v1
kind: Namespace
metadata:
  name: ccnp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: ccnp
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"] # Adjust the verbs as needed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: ccnp
subjects:
- kind: ServiceAccount
  name: default
  namespace: ccnp
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-qs-pod
  namespace: ccnp
  labels:
    app: sleep-qs-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep-qs-pod
  template:
    metadata:
      labels:
        app: sleep-qs-pod
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: sleep-container
        image: curlimages/curl 
        imagePullPolicy: IfNotPresent
        command: ["/bin/sleep", "infinity"]
      - name: pod-quote
        image: docker.io/library/ccnp-pod-quote:0.1
        imagePullPolicy: IfNotPresent
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          limits:
            tdx.intel.com/tdx-guest: 1
        volumeMounts:
          - name: podinfo
            mountPath: /etc/podinfo
      nodeSelector:
        intel.feature.node.kubernetes.io/tdx-guest: "enabled"
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "label"
                fieldRef:
                  fieldPath: metadata.labels
