# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ccnp.quote import quote_server_pb2 as ccnp_dot_quote_dot_quote__server__pb2


class GetQuoteStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetQuote = channel.unary_unary(
                '/quoteserver.GetQuote/GetQuote',
                request_serializer=ccnp_dot_quote_dot_quote__server__pb2.GetQuoteRequest.SerializeToString,
                response_deserializer=ccnp_dot_quote_dot_quote__server__pb2.GetQuoteResponse.FromString,
                )


class GetQuoteServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetQuote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetQuoteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetQuote': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuote,
                    request_deserializer=ccnp_dot_quote_dot_quote__server__pb2.GetQuoteRequest.FromString,
                    response_serializer=ccnp_dot_quote_dot_quote__server__pb2.GetQuoteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quoteserver.GetQuote', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GetQuote(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/quoteserver.GetQuote/GetQuote',
            ccnp_dot_quote_dot_quote__server__pb2.GetQuoteRequest.SerializeToString,
            ccnp_dot_quote_dot_quote__server__pb2.GetQuoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
