# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ccnp/quote/quote-server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x63\x63np/quote/quote-server.proto\x12\x0bquoteserver\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\xa6\x01\n\x13HealthCheckResponse\x12>\n\x06status\x18\x01 \x01(\x0e\x32..quoteserver.HealthCheckResponse.ServingStatus\"O\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x12\x13\n\x0fSERVICE_UNKNOWN\x10\x03\"3\n\x0fGetQuoteRequest\x12\x11\n\tuser_data\x18\x01 \x01(\t\x12\r\n\x05nonce\x18\x02 \x01(\t\"5\n\x10GetQuoteResponse\x12\r\n\x05quote\x18\x01 \x01(\t\x12\x12\n\nquote_type\x18\x02 \x01(\t2S\n\x08GetQuote\x12G\n\x08GetQuote\x12\x1c.quoteserver.GetQuoteRequest\x1a\x1d.quoteserver.GetQuoteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ccnp.quote.quote_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=46
  _globals['_HEALTHCHECKREQUEST']._serialized_end=83
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=86
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=252
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=173
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=252
  _globals['_GETQUOTEREQUEST']._serialized_start=254
  _globals['_GETQUOTEREQUEST']._serialized_end=305
  _globals['_GETQUOTERESPONSE']._serialized_start=307
  _globals['_GETQUOTERESPONSE']._serialized_end=360
  _globals['_GETQUOTE']._serialized_start=362
  _globals['_GETQUOTE']._serialized_end=445
# @@protoc_insertion_point(module_scope)
