# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ccnp.eventlog import eventlog_server_pb2 as eventlog__server__pb2


class EventlogStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEventlog = channel.unary_unary(
                '/Eventlog/GetEventlog',
                request_serializer=eventlog__server__pb2.GetEventlogRequest.SerializeToString,
                response_deserializer=eventlog__server__pb2.GetEventlogReply.FromString,
                )


class EventlogServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEventlog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventlogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEventlog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventlog,
                    request_deserializer=eventlog__server__pb2.GetEventlogRequest.FromString,
                    response_serializer=eventlog__server__pb2.GetEventlogReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Eventlog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Eventlog(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEventlog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Eventlog/GetEventlog',
            eventlog__server__pb2.GetEventlogRequest.SerializeToString,
            eventlog__server__pb2.GetEventlogReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
