// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.11.4
// source: proto/eventlog-server.proto

package getEventlog

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EventlogClient is the client API for Eventlog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventlogClient interface {
	GetEventlog(ctx context.Context, in *GetEventlogRequest, opts ...grpc.CallOption) (*GetEventlogReply, error)
}

type eventlogClient struct {
	cc grpc.ClientConnInterface
}

func NewEventlogClient(cc grpc.ClientConnInterface) EventlogClient {
	return &eventlogClient{cc}
}

func (c *eventlogClient) GetEventlog(ctx context.Context, in *GetEventlogRequest, opts ...grpc.CallOption) (*GetEventlogReply, error) {
	out := new(GetEventlogReply)
	err := c.cc.Invoke(ctx, "/Eventlog/GetEventlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventlogServer is the server API for Eventlog service.
// All implementations must embed UnimplementedEventlogServer
// for forward compatibility
type EventlogServer interface {
	GetEventlog(context.Context, *GetEventlogRequest) (*GetEventlogReply, error)
	mustEmbedUnimplementedEventlogServer()
}

// UnimplementedEventlogServer must be embedded to have forward compatible implementations.
type UnimplementedEventlogServer struct {
}

func (UnimplementedEventlogServer) GetEventlog(context.Context, *GetEventlogRequest) (*GetEventlogReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventlog not implemented")
}
func (UnimplementedEventlogServer) mustEmbedUnimplementedEventlogServer() {}

// UnsafeEventlogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventlogServer will
// result in compilation errors.
type UnsafeEventlogServer interface {
	mustEmbedUnimplementedEventlogServer()
}

func RegisterEventlogServer(s grpc.ServiceRegistrar, srv EventlogServer) {
	s.RegisterService(&Eventlog_ServiceDesc, srv)
}

func _Eventlog_GetEventlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventlogServer).GetEventlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Eventlog/GetEventlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventlogServer).GetEventlog(ctx, req.(*GetEventlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Eventlog_ServiceDesc is the grpc.ServiceDesc for Eventlog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Eventlog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Eventlog",
	HandlerType: (*EventlogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEventlog",
			Handler:    _Eventlog_GetEventlog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/eventlog-server.proto",
}
