apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "eventlog-server.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eventlog-server.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "eventlog-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "eventlog-server.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "eventlog-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: change-permissions
          image: busybox
          command:
            - sh
            - -c
            - >
              chown -R 1000:1000 {{ .Values.volumes.eventlogDir }} &&
              chmod 0744 {{ .Values.volumes.eventlogDir }} &&
              chown -R 1000:1000 {{ .Values.volumes.sockDir }} &&
              chmod 0744 {{ .Values.volumes.sockDir }} &&
              chown 1000:1000 {{ .Values.volumes.eventlogEntryMount }} &&
              chmod 0644 {{ .Values.volumes.eventlogEntryMount }} &&
              chown 1000:1000 {{ .Values.volumes.eventlogDataMount }} &&
              chmod 0644 {{ .Values.volumes.eventlogDataMount }}
          volumeMounts:
            - name: {{ .Values.volumes.eventlogVolume }}
              mountPath: {{ .Values.volumes.eventlogDir }}
            - name: {{ .Values.volumes.sockPath }}
              mountPath: {{ .Values.volumes.sockDir }}
            - name: {{ .Values.volumes.eventlogEntry }}
              mountPath: {{ .Values.volumes.eventlogEntryMount }}
            - name: {{ .Values.volumes.eventlogData }}
              mountPath: {{ .Values.volumes.eventlogDataMount }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
    {{- if .Values.service.enable }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
    {{- end }}
          livenessProbe:
            exec:
                command: ["/usr/bin/grpc_health_probe", "-addr=unix:/run/ccnp/uds/eventlog.sock"]
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
                command: ["/usr/bin/grpc_health_probe", "-addr=unix:/run/ccnp/uds/eventlog.sock"]
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Values.volumes.eventlogVolume }}
              mountPath: {{ .Values.volumes.eventlogDir }}
            - name: {{ .Values.volumes.sockPath }}
              mountPath: {{ .Values.volumes.sockDir }}
            - name: {{ .Values.volumes.eventlogEntry }}
              mountPath: {{ .Values.volumes.eventlogEntryMount }}
            - name: {{ .Values.volumes.eventlogData }}
              mountPath: {{ .Values.volumes.eventlogDataMount }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: {{ .Values.volumes.eventlogVolume }}
        hostPath:
          path: {{ .Values.volumes.eventlogDir }}
          type: DirectoryOrCreate
      - name: {{ .Values.volumes.sockPath }}
        hostPath:
          path: {{ .Values.volumes.sockDir }}
          type: DirectoryOrCreate
      - name: {{ .Values.volumes.eventlogData }}
        hostPath:
          path: {{ .Values.volumes.eventlogDataFile }}
          type: File
      - name: {{ .Values.volumes.eventlogEntry }}
        hostPath:
          path: {{ .Values.volumes.eventlogEntryFile }}
          type: File

