# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eventlog-server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65ventlog-server.proto\"\x81\x01\n\x12GetEventlogRequest\x12\x1e\n\x0e\x65ventlog_level\x18\x01 \x01(\x0e\x32\x06.LEVEL\x12$\n\x11\x65ventlog_category\x18\x02 \x01(\x0e\x32\t.CATEGORY\x12\x16\n\x0estart_position\x18\x03 \x01(\x05\x12\r\n\x05\x63ount\x18\x04 \x01(\x05\"-\n\x10GetEventlogReply\x12\x19\n\x11\x65ventlog_data_loc\x18\x01 \x01(\t*.\n\x08\x43\x41TEGORY\x12\x10\n\x0cTDX_EVENTLOG\x10\x00\x12\x10\n\x0cTPM_EVENTLOG\x10\x01*\x1b\n\x05LEVEL\x12\x08\n\x04PAAS\x10\x00\x12\x08\n\x04SAAS\x10\x01\x32\x43\n\x08\x45ventlog\x12\x37\n\x0bGetEventlog\x12\x13.GetEventlogRequest\x1a\x11.GetEventlogReply\"\x00\x42\x61Z_github.com/intel/confidential-cloud-native-primitives/service/eventlog-server/proto/getEventlogb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eventlog_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z_github.com/intel/confidential-cloud-native-primitives/service/eventlog-server/proto/getEventlog'
  _globals['_CATEGORY']._serialized_start=204
  _globals['_CATEGORY']._serialized_end=250
  _globals['_LEVEL']._serialized_start=252
  _globals['_LEVEL']._serialized_end=279
  _globals['_GETEVENTLOGREQUEST']._serialized_start=26
  _globals['_GETEVENTLOGREQUEST']._serialized_end=155
  _globals['_GETEVENTLOGREPLY']._serialized_start=157
  _globals['_GETEVENTLOGREPLY']._serialized_end=202
  _globals['_EVENTLOG']._serialized_start=281
  _globals['_EVENTLOG']._serialized_end=348
# @@protoc_insertion_point(module_scope)
