name: Golangci-lint

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pr-golanglint.yaml'
      - 'service/eventlog-server/**.go'
      - 'service/measurement-server/**.go'
  pull_request:
    paths:
      - '.github/workflows/pr-golanglint.yaml'
      - 'service/eventlog-server/**.go'
      - 'service/measurement-server/**.go'

  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false

      - name: get changed file
        id: changed-files
        uses: tj-actions/changed-files@v14.5
        with:
          separator: ","

      - name: golangci-lint-for-eventlog-server
        if: contains(steps.changed-files.outputs.all_changed_files, 'service/eventlog-server')
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          working-directory: './service/eventlog-server'

      - name: golangci-lint-for-measurement-server
        if: contains(steps.changed-files.outputs.all_changed_files, 'service/measurement-server')
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          working-directory: './service/measurement-server'
