name: Check License

on:
  pull_request:
  workflow_dispatch:

jobs:
  python-license-scan:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Check License
        run: |
          set -ex
          python3 -m pip install liccheck
          for f in $(find -type f -name "requirements.txt"); do
            liccheck -s .github/.license_check.ini -r $f
          done